# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Google Sign In Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Google/SignIn'
  # Pods for Google Sign In Test

  target 'Google Sign In TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Google Sign In TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
